apiVersion: apps/v1
kind: Deployment
metadata:
  name: stack-ai-vector-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stack-ai-vector-db
  template:
    metadata:
      labels:
        app: stack-ai-vector-db
    spec:
      containers:
      - name: stack-ai-vector-db
        image: "franciscoramos3010/stack-ai-vector-db:latest"
        ports:
        - containerPort: 8000
